#!/usr/bin/env bash
# Regenerate the `python-bindings` branch for the periodic upstream PR
# (ArcadeData/arcadedb). Encodes the rule proven on PR #5010:
#
#   The PR surface = upstream's existing bindings/python tree, nothing more.
#   Only file contents change (from our main), plus additions the wheel
#   build / tests / examples strictly need. Fork-only tooling, docs,
#   benchmarks, and result archives never cross.
#
# The branch is NEVER edited directly — it is always regenerated from main,
# so main stays the single source of truth. Usage:
#
#   ./make-upstream-pr-branch.sh            # regenerate + force push
#   ./make-upstream-pr-branch.sh --no-push  # regenerate only
#
# Prereqs: clean working tree; upstream-main synced (./sync-upstream.sh).
set -euo pipefail

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'

BRANCH="python-bindings"
BASE="upstream-main"
SOURCE="main"

# The bindings/python paths upstream tracks (its current tree surface).
INCLUDE_PATHS=(
    "bindings/python/.gitignore"
    "bindings/python/README.md"
    "bindings/python/pyproject.toml"
    "bindings/python/setup.py"
    "bindings/python/examples"
    "bindings/python/scripts"
    "bindings/python/src"
    "bindings/python/tests"
)

# Fork-only content living INSIDE the include paths — pruned after checkout.
EXCLUDE_PATHS=(
    "bindings/python/examples/benchmark_results"
    "bindings/python/examples/scripts"
    "bindings/python/scripts/profile-python"
    "bindings/python/scripts/fix_markdown.py"
    "bindings/python/scripts/list_image_jars_by_size.sh"
    "bindings/python/scripts/build_and_install_locally.sh"
)

PUSH=1
[ "${1:-}" = "--no-push" ] && PUSH=0

if [ -n "$(git status --porcelain | grep -v '^??' || true)" ]; then
    echo -e "${RED}❌ Working tree has uncommitted changes; commit or stash first.${NC}"
    exit 1
fi

ORIG_BRANCH=$(git branch --show-current)

echo -e "${CYAN}🔀 Regenerating ${BRANCH} from ${BASE} with ${SOURCE}'s bindings...${NC}"
git checkout -q -B "$BRANCH" "$BASE"
git rm -rq bindings/python
git checkout "$SOURCE" -- "${INCLUDE_PATHS[@]}"
git rm -rqf --ignore-unmatch "${EXCLUDE_PATHS[@]}"

SUBJECT="Update Python bindings from humemai/arcadedb-embedded-python ($(date +%Y-%m-%d))"
git -c user.name="Taewoon Kim" commit -q -m "$SUBJECT" \
    -m "Regenerated by make-upstream-pr-branch.sh: bindings/python brought to the fork's main state. Scope: the minimum needed to reproduce the wheel build and run the tests and examples."
echo -e "${GREEN}✅ $(git diff --stat "$BASE" HEAD | tail -1)${NC}"

# Guard: the bindings/python surface must match upstream's exactly.
NEW_TOP=$(comm -13 \
    <(git ls-tree --name-only "$BASE" bindings/python/ | LC_ALL=C sort) \
    <(git ls-tree --name-only HEAD bindings/python/ | LC_ALL=C sort))
if [ -n "$NEW_TOP" ]; then
    echo -e "${YELLOW}⚠️  New top-level entries vs upstream (review before pushing):${NC}"
    echo "$NEW_TOP"
fi

if [ "$PUSH" = "1" ]; then
    git push -f origin "$BRANCH"
    echo -e "${GREEN}✅ Force-pushed ${BRANCH}; open/refresh the PR against ArcadeData/arcadedb main.${NC}"
else
    echo -e "${YELLOW}--no-push: branch left local.${NC}"
fi

git checkout -q "$ORIG_BRANCH"
echo -e "${CYAN}💡 Remember: edit the PR title/body by hand — this script only ships the tree.${NC}"
