name: Test Python Bindings

on:
  # Run on any push to any branch
  push:

  # Run on any pull request
  pull_request:

  # Allow being called by other workflows (e.g., release workflow)
  workflow_call:
    inputs:
      skip-build:
        description: 'Skip building wheels (use pre-built artifacts)'
        required: false
        type: boolean
        default: false

  # Allow manual trigger
  workflow_dispatch:

jobs:
  # First job: Build wheels for all platforms (unless skip-build is true)
  build:
    name: Build Wheels
    if: ${{ !inputs.skip-build }}
    uses: ./.github/workflows/build-python-wheels.yml

  # Second job: Test wheels on each platform
  test:
    name: Test arcadedb-embedded (${{ matrix.platform }})
    runs-on: ${{ matrix.runs-on }}
    needs: build
    if: ${{ !inputs.skip-build || success() }}
    strategy:
      # Don't cancel other matrix jobs if one fails
      fail-fast: false
      matrix:
        include:
          - platform: linux/amd64
            runs-on: ubuntu-latest
          - platform: linux/arm64
            runs-on: ubuntu-latest
          - platform: darwin/amd64
            runs-on: macos-13
          - platform: darwin/arm64
            runs-on: macos-latest
          - platform: windows/amd64
            runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Set up Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: '3.11'

      - name: Download pre-built wheel
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          name: wheel-${{ matrix.platform == 'linux/amd64' && 'linux-amd64' || matrix.platform == 'linux/arm64' && 'linux-arm64' || matrix.platform == 'darwin/amd64' && 'darwin-amd64' || matrix.platform == 'darwin/arm64' && 'darwin-arm64' || 'windows-amd64' }}
          path: test-install/

      # Note: Java is NOT required for arcadedb-embedded (JRE is bundled)
      # This package works without any external Java installation!

      - name: Install wheel and test dependencies
        # Skip for linux/arm64: wheel contains ARM64 JRE but host is AMD64
        # (linux/arm64 cannot be tested on AMD64 host without QEMU)
        if: matrix.platform != 'linux/arm64'
        shell: bash
        run: |
          pip install test-install/*.whl pytest pytest-cov requests

      - name: Run pytest on host
        # Skip for linux/arm64: cannot test ARM64 wheel on AMD64 host
        if: matrix.platform != 'linux/arm64'
        id: pytest
        shell: bash
        run: |
          echo "🧪 Testing arcadedb-embedded (with bundled JRE)..."

          # Run pytest with JUnit XML output for structured results
          set +e  # Don't exit on test failures
          pytest bindings/python/tests/ -v --tb=short --color=yes --junitxml=test-results.xml
          PYTEST_EXIT_CODE=$?
          set -e

          # Parse JUnit XML for test counts (cross-platform XML parsing)
          if [ -f "test-results.xml" ]; then
            # Extract counts from testsuite element
            PASSED=$(grep -oE 'tests="[0-9]+"' test-results.xml | grep -oE '[0-9]+' | head -1)
            FAILED=$(grep -oE 'failures="[0-9]+"' test-results.xml | grep -oE '[0-9]+' | head -1)
            SKIPPED=$(grep -oE 'skipped="[0-9]+"' test-results.xml | grep -oE '[0-9]+' | head -1)

            # Default to 0 if not found
            PASSED=${PASSED:-0}
            FAILED=${FAILED:-0}
            SKIPPED=${SKIPPED:-0}

            echo "passed=$PASSED" >> $GITHUB_OUTPUT
            echo "skipped=$SKIPPED" >> $GITHUB_OUTPUT
            echo "failed=$FAILED" >> $GITHUB_OUTPUT

            echo "✅ Test results: $PASSED passed, $SKIPPED skipped, $FAILED failed"
          else
            echo "⚠️ test-results.xml not found"
            exit 1
          fi

          # Exit with pytest's exit code
          exit $PYTEST_EXIT_CODE

      - name: Generate test summary
        if: always()
        shell: bash
        run: |
          echo "## 🧪 Test Results: arcadedb-embedded (${{ matrix.platform }})" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          # Check if pytest was skipped (e.g., linux/arm64)
          if [ "${{ steps.pytest.outcome }}" = "skipped" ]; then
            echo "⏭️ **Status**: SKIPPED (ARM64 wheel tested during build)" >> $GITHUB_STEP_SUMMARY
          elif [ "${{ steps.pytest.outcome }}" = "success" ]; then
            echo "✅ **Status**: PASSED" >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ **Status**: FAILED" >> $GITHUB_STEP_SUMMARY
          fi

          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Metric | Count |" >> $GITHUB_STEP_SUMMARY
          echo "|--------|-------|" >> $GITHUB_STEP_SUMMARY

          # Show test results if pytest ran
          if [ "${{ steps.pytest.outcome }}" != "skipped" ]; then
            echo "| ✅ Passed | ${{ steps.pytest.outputs.passed || 'N/A' }} |" >> $GITHUB_STEP_SUMMARY
            echo "| ⏭️ Skipped | ${{ steps.pytest.outputs.skipped || 'N/A' }} |" >> $GITHUB_STEP_SUMMARY
            echo "| ❌ Failed | ${{ steps.pytest.outputs.failed || 'N/A' }} |" >> $GITHUB_STEP_SUMMARY
          else
            echo "| ℹ️ Host Tests | Skipped (ARM64 wheel on AMD64 host) |" >> $GITHUB_STEP_SUMMARY
            echo "| ✅ Build Tests | Passed (verified during wheel build) |" >> $GITHUB_STEP_SUMMARY
          fi
          echo "" >> $GITHUB_STEP_SUMMARY

          echo "### 📦 Package Info:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          # Get wheel size and analyze contents
          WHEEL_FILE=$(ls test-install/*.whl 2>/dev/null | head -n1)
          if [ -n "$WHEEL_FILE" ]; then
            # Get wheel size (portable way)
            if stat -c%s "$WHEEL_FILE" 2>/dev/null; then
              # Linux
              WHEEL_SIZE_BYTES=$(stat -c%s "$WHEEL_FILE")
            else
              # macOS/BSD
              WHEEL_SIZE_BYTES=$(stat -f%z "$WHEEL_FILE")
            fi
            WHEEL_SIZE_MB=$(python3 -c "print(f'{$WHEEL_SIZE_BYTES / 1024 / 1024:.1f}')")

            # Unzip and analyze components (wheel is a zip file)
            TEMP_DIR=$(mktemp -d)
            unzip -q "$WHEEL_FILE" -d "$TEMP_DIR"

            # Calculate JRE size (look for jre/ directory anywhere)
            JRE_DIR=$(find "$TEMP_DIR" -type d -name "jre" | head -n1)
            if [ -n "$JRE_DIR" ] && [ -d "$JRE_DIR" ]; then
              # Use du with -k for KB (portable across Linux/macOS)
              JRE_SIZE_KB=$(du -sk "$JRE_DIR" | cut -f1)
              JRE_SIZE_MB=$(python3 -c "print(f'{$JRE_SIZE_KB / 1024:.1f}')")
            else
              JRE_SIZE_MB="N/A"
            fi

            # Calculate JAR size (*.jar files)
            JAR_COUNT=$(find "$TEMP_DIR" -name "*.jar" | wc -l | tr -d ' ')
            if [ "$JAR_COUNT" -gt 0 ]; then
              JAR_SIZE_KB=$(find "$TEMP_DIR" -name "*.jar" -exec du -k {} + | awk '{sum+=$1} END {print sum}')
              JAR_SIZE_MB=$(python3 -c "print(f'{$JAR_SIZE_KB / 1024:.1f}')")
            else
              JAR_SIZE_MB="N/A"
            fi

            # Calculate installed size (total uncompressed)
            INSTALLED_SIZE_KB=$(du -sk "$TEMP_DIR" | cut -f1)
            INSTALLED_SIZE_MB=$(python3 -c "print(f'{$INSTALLED_SIZE_KB / 1024:.0f}')")

            rm -rf "$TEMP_DIR"

            echo "- **Wheel Size**: ${WHEEL_SIZE_MB}M (compressed)" >> $GITHUB_STEP_SUMMARY
            echo "- **JRE Size**: ${JRE_SIZE_MB}M (uncompressed)" >> $GITHUB_STEP_SUMMARY
            echo "- **JARs Size**: ${JAR_SIZE_MB}M (uncompressed)" >> $GITHUB_STEP_SUMMARY
            echo "- **Installed Size**: ~${INSTALLED_SIZE_MB}M (total uncompressed)" >> $GITHUB_STEP_SUMMARY
          fi

          echo "- **Platform**: ${{ matrix.platform }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Features**: All ArcadeDB features (some JARs excluded, see jar_exclusions.txt)" >> $GITHUB_STEP_SUMMARY

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: test-results-${{ matrix.platform == 'linux/amd64' && 'linux-amd64' || matrix.platform == 'linux/arm64' && 'linux-arm64' || matrix.platform == 'darwin/amd64' && 'darwin-amd64' || matrix.platform == 'darwin/arm64' && 'darwin-arm64' || 'windows-amd64' }}
          path: test-results.xml
          retention-days: 7

  # Summary job that checks all platforms
  test-summary:
    name: Test Summary
    needs: test
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Check test results
        run: |
          echo "## 🎯 Overall Test Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          if [ "${{ needs.test.result }}" = "success" ]; then
            echo "✅ **All platforms passed testing!**" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "The arcadedb-embedded package has been successfully built and tested." >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "**Package**: arcadedb-embedded (~160MB with bundled JRE)" >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ **Some platforms failed testing**" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "Please check the individual test jobs for details." >> $GITHUB_STEP_SUMMARY
            exit 1
          fi
